### PR TITLE
provide several alternate base images

### LINKED ISSUE #163: build alternate images with OS and software
At the moment all images are built `FROM scratch`. Some users need operating system and application tools like compilers which are not available in a scratch image, see for example #121.

To accomodate those folks let's provide images built from other common "base" images. So as not to pick a particular vendor, let's build a few and tag them uniquely, e.g. `:0.2.0-distroless` and `:0.2.0-alpine`.

Some suggestions for bases follow, please suggest more, thank you!

- [distroless](https://github.com/GoogleContainerTools/distroless) (Debian)
- [Univeral Base Image](https://developers.redhat.com/products/rhel/ubi) (Fedora/RHEL)
- [buildpack-deps](https://hub.docker.com/_/buildpack-deps/) (Debian)
- [Alpine](https://hub.docker.com/_/alpine) (Alpine)

//cc @thschue

### PR DESCRIPTION
**Pull request by joshgav**
Initial spike to support several base images, fixes #163.

Adds images built on Google [distroless](https://github.com/GoogleContainerTools/distroless), Chainguard [distroless](https://github.com/distroless/), and Red Hat [UBI](https://catalog.redhat.com/software/containers/ubi8/ubi/5c359854d70cc534b3a3784e)

The build process for single-server is a bit out of line with the build process for multi-service, so for now I adjusted both separately, but perhaps before we merge this we can unify them on a single build function.

Will see how the GitHub Actions tests go, and I'm going to do another pass to try to clean this up. Sharing now for feedback or additional feature requests.

### CODE REVIEW

**Review by AlexsJones — APPROVED** [review]
great addition

**Comment by joshgav** [comment]
Last commit unifies the microservices and single-server builds to use the same script for docker build at `scripts/build-image.sh`. We'll now be able to add/change functionality for image builds like scanning and signing by augmenting that one script.

**Review by AlexsJones — APPROVED** [review]

**Review by thschue — APPROVED** [review]
lgtm, great addition

**Comment by joshgav** [comment]
Thanks! I ran this release task to tag release images: https://github.com/podtato-head/podtato-head/actions/runs/2933711983

All the new ones are there now, see the list at (for example) <https://github.com/podtato-head/podtato-head/pkgs/container/entry>

**Pull request merged**
