### PR TITLE
Fix/repo mixcase

### PR DESCRIPTION
**Pull request by MxNxPx**
PR purpose:
In order to be able to fork and develop using a mixcase github username various scripts and config files needed updating.

Fixes:
https://github.com/podtato-head/podtato-head/issues/168

Other info:
Updating the scripts to include and reference new variable that is a lowercase version of the github username and setting some places where a tag of :0.2.7 was referenced to :latest fixed my fork.

### CODE REVIEW

**Comment by MxNxPx** [comment]
@joshgav - i think the delivery checks are failing due to this error:
`denied: installation not allowed to Write organization package
`
https://github.com/podtato-head/podtato-head/runs/7861081061?check_suite_focus=true#step:3:93

makes me believe that the delivery test k8s deployments are referencing an image that wasn't pushed successfully and never get into a running state.

worked fine in my repo's GHA run:
https://github.com/MxNxPx/podtato-head/actions/runs/2868894000

**Comment by MxNxPx** [comment]
> `denied: installation not allowed to Write organization package `

I don't have access to check, but perhaps this configuration of the repo's GITHUB_TOKEN under "Settings">"Actions">"General">"Workflow permissions" needs to be "Read and write permissions" ?

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#configuring-the-default-github_token-permissions

**Comment by joshgav** [comment]
Thanks for this @MxNxPx, great catch and fix. Question: do we need to retain the original mixed-case `github_user` variable? I see a couple places where it's still used in the scripts but it seems likely the lowercased version would work in those cases too. Could you instead change the previous line to `github_user=${GITHUB_USER,,}` and run everything? If that works it'll be a bit cleaner. If you don't mind maybe put a comment in at least one place about what `,,` does and that we need it cause some URLs must be lower case.

Sometimes tests fail for PRs cause PRs can't push a fresh image, but you didn't change the image. So I just ran a couple [release tasks](https://github.com/podtato-head/podtato-head/actions/workflows/release-tasks.yaml) to make sure the `latest` tag is the same as `0.2.7` and will restart your tests too.

Thanks for fixing the `0.2.7` -> `latest` BTW, it gets tricky coordinating test time and releases. That's why I made the "release" task a manual operation for now.

**Comment by joshgav** [comment]
FYI some tests still fail but don't worry about it, it probably has to do with pull secrets etc. I'll try to investigate next week so we can refine for the future.

**Comment by MxNxPx** [comment]
> 

hi @joshgav good feedback.  i have made that adjustment you suggested but since the scripts allow for being executed with passed in args or defaulting to an existing environment variable i had to do it a bit differently to catch both cases.  end result is the same as you requested.  i tested locally and also my fork also ran GHA tests successfully.  let me know if you see an issue with this approach or if it is good.

**Comment by joshgav** [comment]
Looks great, @MxNxPx! And the tests pass now! Thank you.

**Review by joshgav — APPROVED** [review]
LGTM

**Pull request merged**
